language: node_js
node_js:
- '0.11'
- '0.10'
services:
- postgresql
env:
- DATABASE_URL=postgres://postgres@localhost/tss
before_script:
- psql -c "create database tss;" -U postgres
- node_modules/db-migrate/bin/db-migrate up
